kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
  namespace: stage

spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      namespace: stage
      labels:
        app: myapp

    spec:
      serviceAccountName: discoverer
      containers:
        - name: myapp
          image: mix-cluster
          imagePullPolicy: IfNotPresent

          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"

          tty: true
          stdin: true

          # envFrom:
          #   - secretRef:
          #     name: erl_cookie

          env:
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: erl-cookie
                  key: ERLANG_COOKIE
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: myapp-svc-headless
            - name: APP_NAME
              value: myapp
          ports:
            - containerPort: 4369 # <=> "port" in service
              name: epmd
              protocol: TCP
