---
kind: Service
apiVersion: v1
metadata:
  name: my-elixir-app-svc-headless
  namespace: test
  labels:
    app.kubernetes.io/name: my-elixir-app
    app.kubernetes.io/instance: myapp-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    app.kubernetes.io/name: my-elixir-app
    app.kubernetes.io/instance: myapp-node
