version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.release
      args:
        - REL_NAME=a
        - MIX_ENV=dev
    tty: true
    # stdin_open: true
    environment:
      - MIX_ENV=dev

  redis:
    image: redis:7.0.0-alpine
    command: "redis-server"
    ports:
      - 6379:6379

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    volumes:
      - nginxdata:/etc/nginx
    ports:
      - 8080:80

  nginx_conf_generator:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /tmp/templates/:/etc/docker-gen/templates
      - nginxdata:/etc/nginx

volumes:
  nginxdata: