FROM elixir:1.13.4-alpine AS build

ARG MIX_ENV
ENV MIX_ENV=${MIX_ENV:-dev}

WORKDIR /app
# Hex package manager && rebar (Erlang build tool)
RUN mix local.hex --force && mix local.rebar — force

CMD ["sh"]


