FROM elixir:1.13.4-alpine AS build

ARG MIX_ENV
ENV MIX_ENV=${MIX_ENV:-dev}
# ENV HEX_MIRROR=https://repo.hex.pm

RUN apk --update --no-cache add bash curl
WORKDIR /app
# Hex package manager && rebar (Erlang build tool)
RUN mix local.hex --force  && mix local.rebar
COPY mix.exs mix.lock ./
COPY config/ ./config
RUN mix deps.get --only $MIX_ENV && mix deps.compile
COPY lib/ ./lib
RUN mix compile
CMD ["sh"]