# Build Stage using a pre-build release launcher
FROM  ctlptl-minikube-registry:base AS build

ARG MIX_ENV=${MIX_ENV:-dev}
ARG REL_NAME=${REL_NAME:-myapp}
# ENV HEX_MIRROR=https://repo.hex.pm
WORKDIR /app
COPY lib ./lib
COPY rel ./rel
RUN mix release ${REL_NAME} --quiet

# Create a non-root user && Transfer ownership to app user
RUN adduser -h /opt/app -D app \
   && chown -R app: _build/


# Final Stage
FROM alpine:latest AS app

# Accept MIX_ENV as build arg
ARG MIX_ENV=${MIX_ENV:-dev}
ARG REL_NAME=${REL_NAME:-myapp}

# Install system dependencies required for your app at runtime
RUN apk --update --no-cache add bash openssl ncurses-libs tini libstdc++ libgcc

# Create a non-root user
RUN adduser -h /app -D app

# Switch to non-root user
USER app

# Set current working directory to app dir
WORKDIR /app

# Copy release dir from build stage
COPY --from=build /app/_build/$MIX_ENV/rel/${REL_NAME} ./

# COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/sbin/tini", "--"] 
# , "/entrypoint.sh"

# Start your app
CMD ["./bin/myapp", "start"]